import Head from 'next/head'
import Image from 'next/image'
import { Inter,Cedarville_Cursive} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Headline from '../components/Headline'
import WhoAreWe from '../components/WhoAreWe'
import Footer from '../components/Footer'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headline/>
     <WhoAreWe></WhoAreWe>
     <Footer></Footer>
    </>
  )
}
