import Head from 'next/head'
import { Inter} from 'next/font/google'
import Headline from '../components/Headline'
import WhoAreWe from '../components/WhoAreWe'
import LandingCard from '@/components/LandingCard'
import SocialTags from '@/components/SocialTags'
import ExploreBrowseTags from '@/components/ExploreBrowseTags'
const inter = Inter({ subsets: ['latin'] })
import { getCardData } from '../../lib/cardData'
import { getHiringCardData } from '../../lib/HiringCardData'
import WeAreHiring from '@/components/WeAreHiring'

export async function getStaticProps() {
  const cardData = await getCardData()
  // Storing data of Hiring Cards from json file
  const hiringCardData=await getHiringCardData();

  return {
    props: { cardData,hiringCardData }
  }
}


export default function Home({cardData,hiringCardData}) {
// console.log(cardData)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headline/>
      {/* <LandingCard></LandingCard> */}
       <div className="flex w-full justify-center items-center my-[5%]">
        <div className="w-fit md:w-4/5 lg:w-3/5 flex flex-col md:flex-row justify-center items-center min-h-fit space-y-6 md:space-x-6 md:space-y-0">
          <div className="flex flex-col justify-center items-center self-center w-full space-y-6">
            <SocialTags></SocialTags>
            {cardData.length !== 0 &&
            cardData.map((d, idx) => {
              return (
                idx<2 ?
                <LandingCard gradBgFrom={d.gradBgFrom} gradBgTo={d.gradBgTo} textBoxBg={d.textBoxBg} imageSrc={d.imageSrc} isDesktop={d.isDesktop} cardTitle={d.cardTitle} cardSubtitle={d.cardSubtitle}/>
                :""
                );
            })}
          </div>
          <div className="flex flex-col justify-center items-center self-center w-full space-y-6">
          {cardData.length !== 0 &&
            cardData.map((d, idx) => {
              return (
                idx>1 ?
                <LandingCard gradBgFrom={d.gradBgFrom} gradBgTo={d.gradBgTo} textBoxBg={d.textBoxBg} imageSrc={d.imageSrc} isDesktop={d.isDesktop} cardTitle={d.cardTitle} cardSubtitle={d.cardSubtitle}/>
                :""
                );
            })}
            <ExploreBrowseTags></ExploreBrowseTags>
          </div>
        </div>
      </div>
       <WeAreHiring cardData={hiringCardData}></WeAreHiring>
      <WhoAreWe></WhoAreWe> 
    </>
  )
}
